#!/bin/bash
tpn=$(ls devops/_build/sovtoken/)

echo "Your current sovtoken debian package: $tpn \n"


fpn=$(ls devops/_build/sovtokenfees/)

echo "Your current sovtoken debian package: $fpn \n"


echo "summoning warlocks to correct debian package names in the pool dockerfile\n"
sed -i -r "s/sovtoken_pkg_name=/sovtoken_pkg_name=$tpn/" "devops/build-scripts/xenial/Pool_Party/Dockerfile"
sed -i -r "s/sovtokenfees_pkg_name=/sovtokenfees_pkg_name=$tpn/" "devops/build-scripts/xenial/Pool_Party/Dockerfile" 

