#!/bin/bash

export MAKE=/usr/bin/make

# This creates the docker containers that are used for packing 
sov_token=$(eval "SRC_DIR_NAME=sovtoken make -C devops/ package_in_docker")
sov_token_fees=$(eval "SRC_DIR_NAME=sovtokenfees make -C devops/ package_in_docker")

# if the dockerfile is outdated this will update it with current version number
prep=$(./devops/build-scripts/xenial/Pool_Party/prep)

# the script calls for debians to be in the Pool_Party directory and this moves them there
mv devops/_build/sovtoken/*.deb devops/build-scripts/xenial/Pool_Party/.
mv devops/_build/sovtokenfees/*.deb devops/build-scripts/xenial/Pool_Party/.

# change to correct directory and begin building the pool
cd devops/build-scripts/xenial/Pool_Party/
docker build -t indy_pool .

# build and expose container
docker run -itd -p 9701-9708:9701-9708 indy_pool
