#+author: Cam Parra

* Sovrin Ledger Payment plugins
  
  This repo contains the plugins to create the Sovrin payment ledger plugins: Token and Fees

** Install

  run the following command: 

  #+BEGIN_SRC bash
    ./build_indy_pool
  #+END_SRC
  
** EZ Development Enviorment 

*** Why cant I use my own local machine as my enviroment? 

    Due to some compatibility issues we have decided that a docker enviroment would be the easiest way
    for any new developer to get setup and start testing their code.
   
*** Requirements 

   - [[https://www.docker.com/get-docker][docker]]
   - [[https://docs.docker.com/compose/][docker-compose]]
   - [[https://github.com/EugenMayer/docker-sync][docker-sync]]
   - ruby
   - gem 

*** Installing docker-sync 

    #+BEGIN_SRC bash
      gem install docker-sync
    #+END_SRC


*** Starting Dev Env 


    *PLEASE OPEN TWO TERMINAL WINDOWS*


    In the first window:

    #+BEGIN_SRC bash
       make start
    #+END_SRC

    This will run docker-sync-stack start. It will compose the docker container
    and mount your local directory.

    In the second window:

    #+BEGIN_SRC bash
       make setup
    #+END_SRC

    This will fix config files and install sovtoken and sovtoken fees


    Now we run our test:

    #+BEGIN_SRC bash
       make test
    #+END_SRC


    when you're all done using sync just use:
    
    #+BEGIN_SRC bash
       make clean 
    #+END_SRC
