FROM ubuntu:xenial
# TODO LABEL maintainer="Name <email-address>"

# generally useful packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    apt-transport-https \
    curl \
    wget \
    vim \
    git \
    procps \
    autoconf \
    automake \
    g++ \
    gcc \
    make \
    pkg-config \
    zip \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository ppa:brightbox/ruby-ng

# install fpm
ENV FPM_VERSION=1.9.3
RUN apt-get update && apt-get install -y --no-install-recommends \
    ruby-childprocess=0.5.9-1ubuntu1
    ruby2.6 \
    ruby2.6-dev \
    && gem install --no-document rake fpm:$FPM_VERSION \
    && rm -rf /var/lib/apt/lists/*

# TODO CMD ENTRYPOINT ...

ENV BASE_ENV_VERSION=0.2.0
