#!/bin/bash

# Automatically added from template:

dpkg -L sovtoken | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'

# End automatically added section

INDY_CONFIG_PATH="/etc/indy/indy_config.py"

remove_plugin()
{
    sed -i "/ENABLED_PLUGINS.append('$1')/d" $INDY_CONFIG_PATH
}

remove_plugin sovtoken
