#!/bin/bash

# Automatically added from template:
if which py3compile >/dev/null 2>&1; then
	py3compile -O -p sovtokenfees /usr/local/lib/python3.5/dist-packages/
fi
# End automatically added section

PLENUM_CONFIG_PATH="/etc/indy/plenum_config.py"

add_plugin_if_missing()
{
	mkdir -p $(dirname $PLENUM_CONFIG_PATH)
	touch $PLENUM_CONFIG_PATH

	if [ $(grep -c "ENABLED_PLUGINS" $PLENUM_CONFIG_PATH) -eq 0 ]; then 
		echo "ENABLED_PLUGINS=[]" >> $PLENUM_CONFIG_PATH	
	fi

	if [ $(grep -c "ENABLED_PLUGINS.*$1" $PLENUM_CONFIG_PATH) -eq 0 ]; then 
		echo "ENABLED_PLUGINS.append('$1')" >> $PLENUM_CONFIG_PATH	
	fi
}

add_plugin_if_missing sovtokenfees
