#!/bin/bash

# Automatically added from template:

dpkg -L sovtokenfees | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'

# End automatically added section

PLENUM_CONFIG_PATH="/etc/indy/plenum_config.py"

remove_plugin()
{
    sed -i "/ENABLED_PLUGINS.append('$1')/d" $PLENUM_CONFIG_PATH
}

remove_plugin sovtokenfees
