FROM sovrin/base:0.2.0-xenial
# TODO LABEL maintainer="Name <email-address>"

ARG PYTHON3_VERSION

ENV PYTHON3_VERSION=${PYTHON3_VERSION:-3.5}

# python
RUN apt-get update && apt-get install -y \
        python${PYTHON3_VERSION} \
        python3-pip \
        python-setuptools \
    && rm -rf /var/lib/apt/lists/*

# pypi based packages
RUN pip3 install -U \ 
        'pip<10.0.0' \
        'setuptools<=50.3.2' \
        importlib_metadata==2.1.1 \
        importlib_resources==3.2.1 \
        virtualenv==16.0.0 \
        pipenv==2018.11.26

# TODO CMD ENTRYPOINT ...

ENV PYTHON3_ENV_VERSION=0.1.0
